export const appData = [
    {
        Id : 1,
        Category: "Fruit",
        Item: "Apple",
        Count: 1,
        PriceInRs: 10,
    },
    {
        Id : 2,
        Category: "Dairy",
        Item: "Cheese",
        Count: 1,
        PriceInRs: 20,
    },
    {
        Id : 3,
        Category: "Soft Drink",
        Item: "Mountain Dew",
        Count: 1,
        PriceInRs: 35,
    },
    {
        Id : 1,
        Category: "Vegetable",
        Item: "Potato",
        Count: 6,
        PriceInRs: 25,
    },
    {
        Id : 4,
        Category: "Stationery",
        Item: "Pen",
        Count: 1,
        PriceInRs: 5,
    },
    {
        Id : 5,
        Category: "Bakery",
        Item: "Cake",
        Count: 1,
        PriceInRs: 40,
    },
    {
        Id : 6,
        Category: "Fruit",
        Item: "Mango",
        Count: 5,
        PriceInRs: 25,
    },
    {
        Id : 7,
        Category: "Cookware",
        Item: "Spatula",
        Count: 1,
        PriceInRs: 30,
    },
    {
        Id : 8,
        Category: "Vegetable",
        Item: "Onion",
        Count: 9,
        PriceInRs: 60,
    }
];